#!/bin/bash -x

. ${OPENSHIFT_DATA_DIR}env.sh

conda install \
    -c https://conda.binstar.org/ric \
    --yes --file ${OPENSHIFT_REPO_DIR}conda-spec.txt

# currently not used/needed
#pip install -r $OPENSHIFT_REPO_DIR/pip-requirements.txt
