#!/bin/bash

MINICONDA_VERSION=3.4.2

if [ ! -d ${OPENSHIFT_DATA_DIR}anaconda ]; then
    pushd $OPENSHIFT_TMP_DIR
    wget http://repo.continuum.io/miniconda/Miniconda-${MINICONDA_VERSION}-Linux-x86_64.sh
    /bin/bash ./Miniconda-${MINICONDA_VERSION}-Linux-x86_64.sh -b -p ${OPENSHIFT_DATA_DIR}anaconda
    rm Miniconda-${MINICONDA_VERSION}-Linux-x86_64.sh
    popd
fi

if [ ! -d ${OPENSHIFT_DATA_DIR}anaconda/envs/conda-env ]; then
    PATH=${OPENSHIFT_DATA_DIR}anaconda/bin:$PATH \
	conda create --yes -n conda-env python 
fi

if [ ! -f ${OPENSHIFT_DATA_DIR}env.sh ]; then
    echo "export PATH=\${OPENSHIFT_DATA_DIR}anaconda/bin:\$PATH" >> ${OPENSHIFT_DATA_DIR}env.sh
    echo "source activate conda-env" >> ${OPENSHIFT_DATA_DIR}env.sh
fi

# make sure the static dir exists
mkdir -p ${OPENSHIFT_REPO_DIR}static

