#!/usr/bin/python
import os

def application(environ, start_response):
    ctype = 'text/plain'
    response = ['%s: %s' % (key, value)
                     for key, value in sorted(environ.items())]
    response = '\n'.join(response)

    status = '200 OK'
    headers = [
        ('Content-Type', 'text/plain'),
        ('Content-Length', str(len(response))),
        ]

    start_response(status, headers)
    return [response]
